//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long commentId { get; set; }
        public long userId { get; set; }
        public long imgId { get; set; }
        public string comment { get; set; }
        public System.DateTime uploadDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Image Image { get; set; }
    }
}
