//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.Photogram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exif
    {
        public string infoType { get; set; }
        public decimal value { get; set; }
        public long imgId { get; set; }
    
        public virtual Image Image { get; set; }

        public override bool Equals(object obj)
        {
            var exif = obj as Exif;
            return exif != null &&
                   infoType == exif.infoType &&
                   value == exif.value &&
                   imgId == exif.imgId;
        }

        public override int GetHashCode()
        {
            var hashCode = -1283829760;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(infoType);
            hashCode = hashCode * -1521134295 + value.GetHashCode();
            hashCode = hashCode * -1521134295 + imgId.GetHashCode();
            return hashCode;
        }
    }
}
