//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        internal static string lnkChangePwd {
            get {
                return ResourceManager.GetString("lnkChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string lnkHome {
            get {
                return ResourceManager.GetString("lnkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string lnkLogin {
            get {
                return ResourceManager.GetString("lnkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        internal static string lnkLogout {
            get {
                return ResourceManager.GetString("lnkLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        internal static string lnkRegister {
            get {
                return ResourceManager.GetString("lnkRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string lnkSearch {
            get {
                return ResourceManager.GetString("lnkSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Profile.
        /// </summary>
        internal static string lnkUpdateProfile {
            get {
                return ResourceManager.GetString("lnkUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload.
        /// </summary>
        internal static string lnkUploadImg {
            get {
                return ResourceManager.GetString("lnkUploadImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandatory Field.
        /// </summary>
        internal static string mandatoryField {
            get {
                return ResourceManager.GetString("mandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
    }
}
